### ISSUE TITLE
Do you know what happened to the origin project ?

### ISSUE THREAD

**Issue by alterphp** [thepricehub/payment-sips-bundle#1]
Github user kptivestudio seems disappeared... Any information ?

**Comment by na-ji** [comment]
Yes, the account kptivestudio disappeared seven days ago. We do not have any information. We just uploaded this copy so our dependencies does not break.

**Comment by alterphp** [comment]
Thanks. I've got the information that the company has closed ...

**Comment by na-ji** [comment]
It's too bad, but they should not have closed the github account. The old repo have more than 15k downloads on packagist, which is still a lot.
